import type { Metadata } from "next";
import localFont from "next/font/local";
import { DM_Sans } from 'next/font/google'
import "./globals.css";

const dm = DM_Sans({ subsets: ["latin"]}) 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dm.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
